{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnboundLocalError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftPy0B4Typea","text":"PyType","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PyType"}]}]}],"hierarchy":{"paths":[["doc:\/\/SwiftPy\/documentation\/SwiftPy","doc:\/\/SwiftPy\/documentation\/SwiftPy\/Swift","doc:\/\/SwiftPy\/documentation\/SwiftPy\/Swift\/Int16"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftpy\/swift\/int16\/unboundlocalerror"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnboundLocalError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftPy0B4Typea","text":"PyType"}],"symbolKind":"property","roleHeading":"Type Property","role":"symbol","modules":[{"name":"SwiftPy","relatedModules":["Swift"]}],"title":"UnboundLocalError","extendedModule":"Swift","externalID":"s:s5Int16V7SwiftPyE17UnboundLocalErrorABvpZ"},"identifier":{"url":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/Swift\/Int16\/UnboundLocalError","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://SwiftPy/documentation/SwiftPy/PyType":{"url":"\/documentation\/swiftpy\/pytype","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PyType"}],"navigatorTitle":[{"kind":"identifier","text":"PyType"}],"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PyType","abstract":[],"type":"topic","kind":"symbol","title":"PyType"},"doc://SwiftPy/documentation/SwiftPy/Swift":{"kind":"symbol","url":"\/documentation\/swiftpy\/swift","type":"topic","title":"Swift","role":"collection","abstract":[],"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/Swift"},"doc://SwiftPy/documentation/SwiftPy":{"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy","title":"SwiftPy","role":"collection","url":"\/documentation\/swiftpy","abstract":[],"kind":"symbol","type":"topic"},"doc://SwiftPy/documentation/SwiftPy/Swift/Int16/UnboundLocalError":{"kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnboundLocalError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PyType","preciseIdentifier":"s:7SwiftPy0B4Typea","kind":"typeIdentifier"}],"title":"UnboundLocalError","url":"\/documentation\/swiftpy\/swift\/int16\/unboundlocalerror","type":"topic","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/Swift\/Int16\/UnboundLocalError","role":"symbol"},"doc://SwiftPy/documentation/SwiftPy/Swift/Int16":{"fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int16","preciseIdentifier":"s:s5Int16V"}],"navigatorTitle":[{"kind":"identifier","text":"Int16"}],"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/Swift\/Int16","kind":"symbol","abstract":[],"title":"Int16","role":"symbol","type":"topic","url":"\/documentation\/swiftpy\/swift\/int16"}}}