{"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/errorDescription","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/failureReason","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/helpAnchor","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/recoverySuggestion"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/SwiftPy\/documentation\/SwiftPy","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/LocalizedError-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftpy\/pythonerror\/localizederror-implementations"]}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"LocalizedError Implementations","modules":[{"name":"SwiftPy"}]},"references":{"doc://SwiftPy/documentation/SwiftPy/PythonError/helpAnchor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","url":"\/documentation\/swiftpy\/pythonerror\/helpanchor","kind":"symbol","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/helpAnchor","title":"helpAnchor","abstract":[]},"doc://SwiftPy/documentation/SwiftPy":{"type":"topic","abstract":[{"text":"A fast and lightweight Python interpreter with Swift macro binding tools.","type":"text"}],"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy","kind":"symbol","role":"collection","url":"\/documentation\/swiftpy","title":"SwiftPy"},"doc://SwiftPy/documentation/SwiftPy/PythonError":{"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PythonError","kind":"identifier"}],"title":"PythonError","navigatorTitle":[{"text":"PythonError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/swiftpy\/pythonerror","type":"topic","role":"symbol","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError"},"doc://SwiftPy/documentation/SwiftPy/PythonError/errorDescription":{"type":"topic","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/swiftpy\/pythonerror\/errordescription","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/errorDescription"},"doc://SwiftPy/documentation/SwiftPy/PythonError/recoverySuggestion":{"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/recoverySuggestion","url":"\/documentation\/swiftpy\/pythonerror\/recoverysuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[],"title":"recoverySuggestion"},"doc://SwiftPy/documentation/SwiftPy/PythonError/failureReason":{"type":"topic","title":"failureReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/swiftpy\/pythonerror\/failurereason","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/failureReason"}}}